# Generated by Django 5.2.4 on 2025-07-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('link_partitura', models.URLField(blank=True, null=True)),
                ('duracao_treino', models.PositiveIntegerField(help_text='Duração sugerida do treino em minutos')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(auto_now_add=True)),
                ('tempo_praticado', models.PositiveIntegerField(blank=True, help_text='Tempo praticado em minutos', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_guitarra.musica')),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_guitarra.treino')),
            ],
        ),
        migrations.CreateModel(
            name='MusicaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(blank=True, help_text='Ordem da música no treino', null=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_guitarra.musica')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_guitarra.treino')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('treino', 'musica')},
            },
        ),
    ]
